
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplecalculatorapp-deployment
  labels:
    app: calculatorapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculatorapp
  template:
    metadata:
      labels:
        app: calculatorapp 
    spec:
      containers:
      - name: calculatorserver
        image: thetips4you/nodeapp:latest
        ports:
        - containerPort: 5000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: calculatorapp-service
spec:
  selector:
    app: calculatorapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 5000