apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-calculator-app
  name: simple-calculator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-calculator-app
  template:
    metadata:
      labels:
        app: simple-calculator-app
    spec:
      containers:
      - name: my-simple-calculator-app
        image: pramod858/simple-calculator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-calculator-app
    k8s-app: simple-calculator-app
  name: simple-calculator-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer
  selector:
    app: simple-calculator-app